### PR TITLE
Migrated changes unmerged in previous repo...

### PR DESCRIPTION
**Pull request by tomasg2012**
changes include:
Handlers now all use similar arguments
Fixed grammar/logic for Revision, Status, Reference
Fixed Identity
Temporary preprocessing fix to comment removal
issues with certain YANG files fixed
Augment places generated info in its own xml files

### CODE REVIEW

**Comment by mraineri** [comment]
From 12/14: Will let @jcleung5549 test this before accepting

**Comment by jcleung5549** [comment]
The resultant xml files have a regression. In annotations, the 'Term' field should come first.   In the output below, the Description annotate has the 'Term' field last.

```
<NavigationProperty Name="interfacesContainer" ContainsTarget="True" Type="interfaces.interfaces">
    <Annotation Term="OData.Permissions" EnumMember="OData.Permissions/Read"/>
    <Annotation String="Navigation property that points to a resource of interfaces." Term="OData.Description"/>
    <Annotation String="Automatically generated." Term="OData.LongDescription"/>
    <Annotation Term="AutoExpandReferences"/>
</NavigationProperty>
```

**Comment by jcleung5549** [comment]
The problem is not in the converter, it's in the application used to view the XML file.  Explorer and Edge reorder the attributes.  VIM or Notepad preserve the ordering.

Merge approved.

**Comment by mraineri** [comment]
Approved 1/4

**Pull request merged**
